---
# Ranges
gost:
    latin:      >
                26 41-5a 61-7a c4 e4 d5 d6 dc df f5 f6 fc
                100 101 104 105 10c 10d 112 113 116-119
                122 123 12a 12b 12e 12f 136 137 13b 13c 145 146
                160 161 16a 16b 172 173 17d 17e
    cyrillic:   >
                401 404 406-408 40e-44f 451 454 456-458 45e
                492-4c2 4cf-4d9 4dc-4e9 4ee-4f5 4f8-4f9
    armenian:   531-556 561-587
    georgian:   10d0-10f0
    digits:     21 27-29 2c-2e 3f 30-39 ab bb 2013 2116

unicode:
    latin:      >
                41-5a 61-7a 7f-aa c0-2e4 1d00-1dbe 1e00-1eff 2071 207f
                2090-209c 212a 212b 2132 214e 2200-2204 249c-24e9 2c60-2c7f
                3271-33df a722-a7ff ab30-ab64 fb00-fb06 ff21-ff5a
    greek:      370-3ff 1f00-1fff
    cyrillic:   400-4ff 500-52f 1c80-1c8f 2de0-2dff a640-a69f
    armenian:   530-58f
    hebrew:     590-5ff
    georgian:   10a0-10ff
    digits:     >
                0-3f 5b-60 7b-7e ab ac af-bf 300-361
                2000-2070 2072-207e 2080-208e 2150-218b 23e8 2460-249b 24ea-24ff
                2753-2755 2757 275b-2762 2768-2793 2795-2797 2e00-2e42 3000-3037
                3248-324f 3251-325f 32b1-32bf

# Character sets used in alphabets
# use
#   perl -CS -MList::Util=uniq -0777 -nE 'say join "", sort(uniq(split ""))'
# to extract alphabet from text
alphabet:
    Abaza:          ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёӀ
    Abkhaz:         ЏАБВГДЕЖЗИКЛМНОПРСТУФХЦЧШЫЬабвгдежзиклмнопрстуфхцчшыьџҔҕҚқҞҟҦҧҨҩҬҭҲҳҴҵҶҷҼҽҾҿӘәӠӡӶӷԤԥ
    Adyghe:         IЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяё
    Aghul:          IЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяё
    Altai:          ЁЈАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёјҤҥӦӧӰӱ
    Armenian:       ԱԲԳԴԵԶԷԸԹԺԻԼԽԾԿՀՁՂՃՄՅՆՇՈՉՊՋՌՍՎՏՐՑՒՓՔՕՖաբգդեզէըթժիլխծկհձղճմյնշոչպջռսվտրցւփքօֆև
    Avar:           ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЭЮЯабвгдежзийклмнопрстуфхцчшщъьэюяёӀ
    Azeri_Cyr:      ЈАБВГДЕЖЗИКЛМНОПРСТУФХЧШЫабвгдежзиклмнопрстуфхчшыјҒғҜҝҮүҸҹҺһӘәӨө
    Azeri_Lat:      ABCDEFGHIJKLMNOPQRSTUVXYZabcdefghijklmnopqrstuvxyzÇÖÜçöüĞğİıŞşƏə
    Bashkir:        ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёҒғҘҙҠҡҢңҪҫҮүҺһӘәӨө
    Bulgarian:      АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЬЮЯабвгдежзийклмнопрстуфхцчшщъьюя
    Buryat:         ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёҮүҺһӨө
    Byelorussian:   ЁІЎАБВГДЕЖЗЙКЛМНОПРСТУФХЦЧШЫЬЭЮЯабвгдежзйклмнопрстуфхцчшыьэюяёіў
    Chechen:        ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёӀ
    Chukchi:        ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёӃӄӇӈԒԓ
    Chuvash:        ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёҪҫӐӑӖӗӲӳ
    Crimean_Tatar_Lat:  ABCDEFGHIJKLMNOPQRSTUVYZabcdefghijklmnopqrstuvyzÇÑÖÜçñöüĞğİıŞş
    Crimean_Tatar_Cyr:  ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяё
    Croatian:       ABCDEFGHIJKLMNOPRSTUVZabcdefghijklmnoprstuvxzÐĆćČčđŠšŽž
    Czech:          ABCDEFGHIJKLMNOPQRSTUVWXYZhÁÉÍÓÚÝČĎĚŇŘŠŤŮŽabcdefghijklmnopqrstuvwxyzháéíóúýčďěňřšťůž
    Danish:         ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÅÆØåæø
    Dargin:         ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёӀ
    Dolgan:         ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёҮүҺһӇӈӨө
    English:        ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
    Esperanto:      ABCDEFGHIJKLMNOPRSTUVZabcdefghijklmnoprstuvzĜĝĤĥĴĵŜŝŬŭ
    Estonian:       ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÄÕÖÜäõöüŠšŽž
    Even:           ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёӇӈӨөӪӫ
    Evenki:         ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёӇӈ
    Faroese:        ABDEFGHIJKLMNOPRSTUVYabdefghijklmnoprstuvyÁÆÍÐÓØÚÝáæíðóøúý
    Finnish:        ABCDEFGHIJKLMNOPQRSTUVWXYZ[]abcdefghijklmnopqrstuvwxyzÄÅÖäåæöŽž
    French:         ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÀÂÆÇÈÉÊËÎÏÔÙÛÜàâæçèéêëîïôùûüÿŒœŸ
    Georgian:       აბგდევზთიკლმნოპჟრსტუფქღყშჩცძწჭხჯჰ
    German:         ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÄÖÜßäöü
    Hungarian:      ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÁÉÍÓÖÚÜáéíóöúüŐőŰű
    Icelandic:      ABDEFGHIJKLMNOPRSTUVXYabdefghijklmnoprstuvxyÁÆÉÍÐÓÖÚÝÞáæéíðóöúýþ
    Ingush:         ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёӀ
    Italian:        ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÀÁÈÉÌÍÒÓÙÚàáèéìíòóùú
    Kabardian:      ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёӀ
    Kalmyk:         ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёҖҗҢңҮүҺһӘәӨө
    Karachay_Balkar:    ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяё
    Karelian:       ABCDEFGHIJKLMNOPRSTUVYZabcdefghijklmnoprstuvyzÄÖäöČčŠšŽž
    Kazakh:         ЁІАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёіҒғҚқҢңҮүҰұҺһӘәӨө
    Khakassian:     ЁІАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёіҒғҢңӋӌӦӧӰӱ
    Khanty:         ЄЉЊЎАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяєљњўӃӄӇӈӐӑӒӓӘәӧӨөӰӱӼӽԒԓ
    Komi:           ЁІАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёіӦӧ
    Kirghiz:        ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёҢңҮүӨө
    Kumyk:          ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяё
    Lak:            IЁІАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёӀ
    Latin:          ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÆæŒœ
    Latvian:        ABCDEFGHIJKLMNOPRSTUVZabcdefghijklmnoprstuvzĀāČčĒēĢģĪīĶķĻļŅņŠšŪūŽž
    Lezgian:        ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёӀ
    Lithuanian:     ABCDEFGHIJKLMNOPRSTUVYZabcdefghijklmnoprstuvyzĄąČčĖėĘęĮįŠšŪūŲųŽž
    Macedonian:     ЃЅЈЉЊЌЏАБВГДЕЖЗИКЛМНОПРСТУФХЦЧШабвгдежзиклмнопрстуфхцчшѓѕјљњќџ
    Mansi:          ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёӇӈӢӣӮӯ
    Mari:           ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёҤҥӒӓӦӧӨөӪӫӰӱӸӹ
    Moldovan_Cyr:   АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЫЬЭЮЯабвгдежзийклмнопрстуфхцчшыьэюяӁӂ
    Mongol:         ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёҮүӨө
    Mordvinic:      ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяё
    Nenets:         ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёӇӈ
    Nogai:          ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяё
    Norwegian:      ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÅÆØåæø
    Ossetian:       ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёӔӕ
    Polish:         ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÓóĄąĆćĘęŁłŃńŚśŹźŻż
    Portuguese:     ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÀÁÂÃÇÉÊÍÓÔÕÚàáâãçéêíóôõú
    Romanian:       ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÂÎâîĂăȘșȚț
    Russian:        АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюя
    Rutul:          ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёӀ
    Selkup:         ЁІАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёіӃӄӇӈӒӓӘәӦӧӨөӰӱ
    Serbian:        ЂЈЉЊЋЏАБВГДЕЖЗИКЛМНОПРСТУФХЦЧШабвгдежзиклмнопрстуфхцчшђјљњћџ
    Spanish:        ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÑñÁáÉéÍíÓóÚúÜü
    Swedish:        ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÄÅÖäåö
    Tabasaran:      ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёӀ
    Tadjik:         ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЧШЪЭЮЯабвгдежзийклмнопрстуфхчшъэюяёҒғҚқҲҳҶҷӢӣӮӯ
    Tat:            IЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяё
    Tatar:          ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёҖҗҢңҮүҺһӘәӨө
    Tsakhur:        IЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяё
    Turkish:        ABCDEFGHIJKLMNOPRSTUVYZabcdefghijklmnoprstuvyzÇÖÜçöüĞğİıŞş
    Turkmen_Cyr:    ƏЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёҖҗҢңҮүәӨө
    Turkmen_Lat:    ABDEFGHIJKLMNOPRSTUWYZabdefghijklmnoprstuwyzÄÇÖÜÝäçöüýŇňŞşŽž
    Tuvan:          ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёҢңҮүӨө
    Udmurt:         ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёӜӝӞӟӤӥӦӧӴӵ
    Ukrainian:      ЄІЇАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЬЮЯабвгдежзийклмнопрстуфхцчшщьюяєіїҐґ
    Uzbek_Cyr:      ЁЎАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЪЬЭЮЯабвгдежзийклмнопрстуфхцчшъьэюяёўҒғҚқҲҳ
    Uzbek_Lat:      ABCDEFGHIJKLMNOPQRSTUVXYZabcdefghijklmnopqrstuvxyzʻʼ
    Veps:           ABCDEFGHIJKLMNOPRSTUVZabcdefghijklmnoprstuvzÄÖÜäöüČčŠšŽž
    Yakut:          ЁАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёҔҕҤҥҮүҺһӨө
    Yiddish:        אבגדהוזחטיךכלםמןנסעףפץצקרשתװױײ׳״ﬞﭏ
